<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Nullable>enable</Nullable>
        <Platforms>AnyCPU</Platforms>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <LangVersion>10</LangVersion>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <AllowedReferenceRelatedFileExtensions>none</AllowedReferenceRelatedFileExtensions>
        <DebugType>none</DebugType>
        <OutputPath>$(BuildOutputDir)/plugins</OutputPath>
        <GameDeployPath>$(NuclearOptionPluginDeployPath)</GameDeployPath>
        <SkipGameLayoutStaging>true</SkipGameLayoutStaging>
        <TargetFramework>net48</TargetFramework>
        <RootNamespace>UnityEngine.XR.Management</RootNamespace>
        <AssemblyName>Unity.XR.Management</AssemblyName>
    </PropertyGroup>

    <ItemGroup Condition=" '$(NuclearOptionGameDirResolved)' == 'NUCLEAR_OPTION_NOT_FOUND' ">
        <Reference Include="$(NuclearOptionFallbackLibDir)/*.dll" Exclude="$(NuclearOptionFallbackLibExcludes)">
            <Private>False</Private>
        </Reference>
    </ItemGroup>

    <ItemGroup Condition="'$(RestoreBepInExFromNuget)' == 'true'">
        <PackageReference Include="BepInEx.Core" Version="5.4.16" />
    </ItemGroup>

</Project>
