<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <NuclearOptionGameDirResolved Condition="'$(NuclearOptionGameDirResolved)' == '' And '$(NuclearOptionGameDir)' != ''">$(NuclearOptionGameDir)</NuclearOptionGameDirResolved>
    <NuclearOptionGameDirResolved Condition="'$(NuclearOptionGameDirResolved)' == '' And '$(NUCLEAR_OPTION_GAME_DIR)' != ''">$(NUCLEAR_OPTION_GAME_DIR)</NuclearOptionGameDirResolved>

    <NuclearOptionGameDirResolved Condition="'$(NuclearOptionGameDirResolved)' == '' And Exists('$(HOME)/Locations/NuclearOption/Install/NuclearOption_Data/Managed')">$(HOME)/Locations/NuclearOption/Install</NuclearOptionGameDirResolved>
    <NuclearOptionGameDirResolved Condition="'$(NuclearOptionGameDirResolved)' == '' And Exists('$(HOME)/.steam/steam/steamapps/common/Nuclear Option/NuclearOption_Data/Managed')">$(HOME)/.steam/steam/steamapps/common/Nuclear Option</NuclearOptionGameDirResolved>
    <NuclearOptionGameDirResolved Condition="'$(NuclearOptionGameDirResolved)' == '' And Exists('$(HOME)/.steam/debian-installation/steamapps/common/Nuclear Option/NuclearOption_Data/Managed')">$(HOME)/.steam/debian-installation/steamapps/common/Nuclear Option</NuclearOptionGameDirResolved>
    <NuclearOptionGameDirResolved Condition="'$(NuclearOptionGameDirResolved)' == '' And Exists('$(HOME)/.local/share/Steam/steamapps/common/Nuclear Option/NuclearOption_Data/Managed')">$(HOME)/.local/share/Steam/steamapps/common/Nuclear Option</NuclearOptionGameDirResolved>

    <NuclearOptionGameDirResolved Condition="'$(NuclearOptionGameDirResolved)' == '' And Exists('C:\Program Files (x86)\Steam\steamapps\common\Nuclear Option\NuclearOption_Data\Managed')">C:\Program Files (x86)\Steam\steamapps\common\Nuclear Option</NuclearOptionGameDirResolved>
    <NuclearOptionGameDirResolved Condition="'$(NuclearOptionGameDirResolved)' == '' And Exists('C:\Program Files\Steam\steamapps\common\Nuclear Option\NuclearOption_Data\Managed')">C:\Program Files\Steam\steamapps\common\Nuclear Option</NuclearOptionGameDirResolved>
    <NuclearOptionGameDirResolved Condition="'$(NuclearOptionGameDirResolved)' == '' And Exists('D:\SteamLibrary\steamapps\common\Nuclear Option\NuclearOption_Data\Managed')">D:\SteamLibrary\steamapps\common\Nuclear Option</NuclearOptionGameDirResolved>

    <NuclearOptionGameDirResolved Condition="'$(NuclearOptionGameDirResolved)' == ''">NUCLEAR_OPTION_NOT_FOUND</NuclearOptionGameDirResolved>

    <NuclearOptionManagedDir>$(NuclearOptionGameDirResolved)/NuclearOption_Data/Managed</NuclearOptionManagedDir>
    <NuclearOptionBepInExCoreDir>$(NuclearOptionGameDirResolved)/BepInEx/core</NuclearOptionBepInExCoreDir>
    <NuclearOptionPluginDeployPath>BepInEx/plugins/NOVR</NuclearOptionPluginDeployPath>
    <NuclearOptionPatcherDeployPath>BepInEx/patchers/NOVR</NuclearOptionPatcherDeployPath>
    <NuclearOptionPluginDir Condition="'$(NuclearOptionPluginDir)' == '' And '$(NuclearOptionGameDirResolved)' != 'NUCLEAR_OPTION_NOT_FOUND'">$(NuclearOptionGameDirResolved)/BepInEx/plugins/NOVR</NuclearOptionPluginDir>
    <NuclearOptionPatcherDir Condition="'$(NuclearOptionPatcherDir)' == '' And '$(NuclearOptionGameDirResolved)' != 'NUCLEAR_OPTION_NOT_FOUND'">$(NuclearOptionGameDirResolved)/BepInEx/patchers/NOVR</NuclearOptionPatcherDir>
    <NuclearOptionLocalReferenceExcludes>$(NuclearOptionManagedDir)/Unity.XR.Management.dll;$(NuclearOptionManagedDir)/Unity.XR.OpenXR.dll;$(NuclearOptionManagedDir)/Unity.XR.OpenVR.dll</NuclearOptionLocalReferenceExcludes>
    <RestoreBepInExFromNuget Condition="'$(RestoreBepInExFromNuget)' == '' And Exists('$(NuclearOptionBepInExCoreDir)/BepInEx.dll')">false</RestoreBepInExFromNuget>
    <RestoreBepInExFromNuget Condition="'$(RestoreBepInExFromNuget)' == ''">true</RestoreBepInExFromNuget>
  </PropertyGroup>

  <ItemGroup Condition="'$(NuclearOptionGameDirResolved)' != 'NUCLEAR_OPTION_NOT_FOUND' And '$(SkipNuclearOptionReferences)' != 'true'">
    <Reference Include="$(NuclearOptionManagedDir)/*.dll" Exclude="$(NuclearOptionLocalReferenceExcludes)">
      <Private>False</Private>
    </Reference>
    <Reference Include="$(NuclearOptionBepInExCoreDir)/*.dll" Exclude="$(NuclearOptionBepInExCoreDir)/0Harmony20.dll">
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
